# -*- coding: utf-8 -*-
"""IE313-b03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgJnzm2BQD2M9Eki0RtwvnYS4QInn9CT

- MSSV: 25410291
- Họ Tên: Đinh Xuân Sâm
- GDrive: [IE313-b03.ipynb](https://colab.research.google.com/drive/1LgJnzm2BQD2M9Eki0RtwvnYS4QInn9CT?usp=sharing)

# Buổi 03 - Bài 01 - Load Dataset

## Load Dataset
"""

dataset_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
dataset_file = "imports-85.csv"

# download the dataset file
import requests

response = requests.get(dataset_url)

with open(dataset_file, "wb") as file:
    file.write(response.content)

print("Download complete!")

# dataset headers row
headers = [
"symboling",
"normalized-losses",
"make",
"fuel-type",
"aspiration",
"num-of-doors",
"body-style",
"drive-wheels",
"engine-location",
"wheel-base",
"length",
"width",
"height",
"curb-weight",
"engine-type",
"num-of-cylinders",
"engine-size",
"fuel-system",
"bore","stroke",
"compression-ratio",
"horsepower",
"peak-rpm",
"city-mpg",
"highway-mpg",
"price"]

# import panda
import pandas as pd

"""## `read_csv`"""

# read from a local file
pd.read_csv(dataset_file)

# read file from google drive
pd.read_csv("/content/drive/MyDrive/uit/courses/IE313/06_Dataset/imports-85.csv")

# read file from google drive with headers
df = pd.read_csv("/content/drive/MyDrive/uit/courses/IE313/06_Dataset/imports-85.csv", names=headers)

df

"""## Select a certain column/feature"""

# a certain column/series
df['make']

"""## Select multiple columns/features"""

# multiple columns, series
df[['make', 'body-style']]

"""## `.head()`"""

# 5 top row
df.head()

"""## `.tail()`"""

# 10 last row
df.tail(10)

"""## `.sample()`"""

# random sample dataset from the existing dataframe
df.sample()

"""## `.to_csv` and other file formats"""

# save to csv without the index column/series
df.to_csv("dataset_bai01.csv", index=False)

"""## Data Type `.dtypes`"""

# series data types, series types validation
df.dtypes

"""## `.info()`"""

# dataframe info
df.info()

"""## `.describe()`"""

df.describe()

"""# Buổi 03 - Bài 02 - Data Wrangling

## Tiền Xử Lý Dữ Liệu

- Tìm và xử lý giá trị khuyết
- Định dạng dữ liệu
- Chuẩn hóa dữ liệu
- Chuyển giá trị số thành các giá trị phân loại
- Chuyển các giá trị phân loại thành giá trị số

### Xử Lý Giá Trị Bị Khuyết
"""

# none NA df
pd.DataFrame(data = {
    'a': [1, 2, 3, 4, 5],
    'b': [6, 7, 8, 9, 10],
    'c': [11, 12, 13, 14, 15]
})

import numpy as np

# np.NA df
pd.DataFrame(data = {
    'a': [1, np.nan, 3, 4, 5],
    'b': [np.nan, 7, 8, 9, '?'],
    'c': [11, 12, 13, np.nan, 15]
})

"""#### Loại Bỏ Giá Trị Khuyết (`.dropna()`)"""

# dropna sample
pd.DataFrame(data = {
    'a': [1, np.nan, 3, 4, 5],
    'b': [np.nan, 7, 8, 9, '?'],
    'c': [11, 12, 13, np.nan, 15]
}).dropna()

# dropna sample
pd.DataFrame(data = {
    'a': [1, np.nan, 3, 4, 5],
    'b': [np.nan, 7, 8, 9, '?'],
    'c': [11, 12, 13, np.nan, 15]
}).dropna(subset=['a'])

"""#### Thay Thế Giá Trị Khuyết (`.replace()`)"""

# replace sample
df2 = pd.DataFrame(data = {
    'a': [1, np.nan, 3, 4, 5],
    'b': [np.nan, 7, 8, 9, '?'],
    'c': [11, 12, 13, np.nan, 15]
})

df2['c'].replace(to_replace=np.nan, value=df2['c'].mean())

"""### Định Dạng Dữ Liệu

- `replace()`
- Chuyển đổi: `df['city-L/100km'] = 235/df['city-mpg']`
- Cập nhật kiểu dữ liệu: `DataFrame[Series] = DataFrame[Series].astype('datatype')`

### Chuẩn Hóa Dữ Liệu
"""

from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

df['length_zscore'] = ss.fit_transform(df[['length']])

df.info()