# -*- coding: utf-8 -*-
"""IE313-b03-Bai02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N-pNcXCixloVnUNra3I9uUEtx3ix6WB7

# Buổi 03 - Bài 02 - Bài Tập Tổng Hợp

- MSSV: 25410291
- Họ Tên: Đinh Xuân Sâm
- GDrive: [IE313-b03-Bai02.ipynb](https://colab.research.google.com/drive/1N-pNcXCixloVnUNra3I9uUEtx3ix6WB7?usp=sharing)

Yêu cầu:

Sử dụng bộ dữ liệu thô ở chương 1 (link trong slide). Sau đó, tiến hành xử lý theo quy trình sau:

1. Cột `price` => `dropna` => dòng.
2. Cột `horsepower` => `replace` => `mean`.
3. Cột `normalized-losses` => `replace` => `mode`.
4. Bước cuối cùng, `dropna` dòng cho toàn bộ dữ liệu.
5. Quan sát giá trị thực tế, sau đó chuyển kiểu phù hợp cho các cột còn lại.
6. Chọn ra các cột số, chuẩn hóa thành `zscore`.

Nộp file code dạng `ipynb`.

## 0. Nạp Dữ Liệu
"""

# Đạt biến chứa url/tên và nếu dùng gdrive cho dataset
dataset_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data"
dataset_file = "imports-85.csv"
dataset_file_gdrive = "/content/drive/MyDrive/uit/courses/IE313/06_Dataset/imports-85.csv"

# Tải dataset
import requests

response = requests.get(dataset_url)

with open(dataset_file, "wb") as file:
    file.write(response.content)

print("Download complete!")

# dataset headers
headers = [
"symboling",
"normalized-losses",
"make",
"fuel-type",
"aspiration",
"num-of-doors",
"body-style",
"drive-wheels",
"engine-location",
"wheel-base",
"length",
"width",
"height",
"curb-weight",
"engine-type",
"num-of-cylinders",
"engine-size",
"fuel-system",
"bore","stroke",
"compression-ratio",
"horsepower",
"peak-rpm",
"city-mpg",
"highway-mpg",
"price"]

# import panda
import pandas as pd

# đọc file dataset với headers chỉ định
df = pd.read_csv(dataset_file, names=headers)

# df quick look
df

"""## 1. Cột `price` => `dropna` => dòng."""

# Kích thước của df hiện tại
df.shape

# Thông tin của df
df.info()

# Kích thước của price
df['price'].shape

# import numpy
import numpy as np

# Thay thế giá trị khuyết tự nhiên thành Numpy N/A và kiểm tra khuyết
df.replace(to_replace='?', value=np.nan, inplace=False).info()

"""### Nhận xét

- `price` có 201 dòng `non-null`, có nghĩa có 4 dòng N/A cần được loại bỏ
"""

# Thay thế giá trị khuyết tự nhiên thành Numpy N/A, inplace
df.replace(to_replace='?', value=np.nan, inplace=True)
df.info()

# Kích thước của price sau khi điền N/A
df['price'].shape

# Kiểm thử trước khi dropna
df.dropna(axis=0, subset=['price'], inplace=False).info()

# Thực hiện dropna và kiểm tra lại kích thước của price
df.dropna(axis=0, subset=['price'], inplace=True)
df['price'].info()

# Kích thước của price sau khi dropna
df['price'].shape

# Kiểm tra lại kích thước của df
df.shape

"""### Kết Quả

- `price` đã được `dropna`.
- Số lượng dòng GIẢM từ 205 xuống 201 (tương ứng số dòng `non-null` đã đề cập trước đó).
- Số dòng của `df` GIẢM tương ứng vì dòng sẽ được xóa tương ứng.

## 2. Cột `horsepower` => `replace` => `mean`.

### Đánh Giá

- `horsepower` hiện đang có kiểu là `object`.
- Cần chuyển kiểu dữ liệu về kiểu số (`float`/`int`) để có thể tính `mean`.
"""

# Lấy sample để đối chiếu kiểu dữ liệu
df.sample()

# Kiểu dữ liệu hiện tại
df.info()

"""Các cột cần đổi kiểu dữ liệu:

```
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object -> float
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64  
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object -> int
 16  engine-size        205 non-null    int64  
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object -> float
 19  stroke             205 non-null    object -> float
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object -> float
 22  peak-rpm           205 non-null    object -> int
 23  city-mpg           205 non-null    int64  
 24  highway-mpg        205 non-null    int64  
 25  price              205 non-null    object -> float
```
"""

# Đổi kiểu dữ liệu để phản ánh đúng kiểu của giá trị
df['horsepower'] = df['horsepower'].astype('float')
df['horsepower'].info()

# Tính mean của horsepower
mean_horsepower = df['horsepower'].mean()
mean_horsepower

# Kiểm tra trước kết quả của phép thay thế NA với mean
df['horsepower'].replace(to_replace=np.nan, value=mean_horsepower, inplace=False).info()

# Thực hiện phép thay thế NA với mean
df['horsepower'].replace(to_replace=np.nan, value=mean_horsepower, inplace=True)
df['horsepower'].info()

# Kiểm tra lại
df['horsepower']

"""### Kết Quả

- `horsepower` đã được đổi kiểu dữ liệu từ `object` thành `float`.
- Các giá trị `NaN` trong `horsepower` đã được thay thế bằng `mean` của `horsepower`.
- Tất cả 201 dòng của `horsepower` hiện đã không chứa bắt kỳ `NaN` nào nữa.

## 3. Cột `normalized-losses` => `replace` => `mode`.
"""

# Xem thông tin của `normalized-lossess`
df['normalized-losses'].info()

# Show N/A
df[df['normalized-losses'].isna()]['normalized-losses']

"""### Đánh Giá

- Tổng 201 dòng.
- Chỉ có 164 dòng có dữ liệu (non-null).
- Kiểu dữ liệu là `object`.

### Kế Hoạch

- Chuyển dữ liệu sang dạng số để có thể tính `mode`.
- Dùng `replace` để thay thế các giá trị null/NaN với `mode`.
- Kiểm tra lại kết quả.
"""

# Convert data type
df['normalized-losses'] = df['normalized-losses'].astype('float')
df['normalized-losses'].info()

# Calculate mode, get the very first value only
mode_normalized_losses = df['normalized-losses'].mode()[0]
mode_normalized_losses

# dry-run/preview the replace method
df['normalized-losses'].replace(to_replace=np.nan, value=mode_normalized_losses, inplace=False).info()

# Apply the replace method
df['normalized-losses'].replace(to_replace=np.nan, value=mode_normalized_losses, inplace=True)
df['normalized-losses'].info()

# Show N/A
df[df['normalized-losses'].isna()]['normalized-losses']

# Preview
df['normalized-losses']

"""### Kết Quả

- `normalized-lossess` đã được thay thế các giá trị null/NaN với mode.
- Hiện tại không còn tồn tại dòng NaN nào trong `normalized-lossess` nữa.

## 4. Bước cuối cùng, `dropna` dòng cho toàn bộ dữ liệu.

### Kế Hoạch

- Xác định kích thước hiện tại của `df`.
- Kiểm tra số lượng hoặc/và xem trước các dòng/cột có NaN trong `df`.
- Thực hiện `dropna`.
- Kiểm tra lại kích thước của `df` và các giá trị NaN nếu còn tồn tại.
"""

# df shape
df.shape

# các dòng có NaN (ở bất kỳ cột nào)
df[df.isna().any(axis=1)]

# drop na for all the dataframe: dry-run
df.dropna(axis=0, subset=df.columns, inplace=False).info()

# drop na for all the dataframe: execute
df.dropna(axis=0, subset=df.columns, inplace=True)
df.info()

# Kiểm tra lại các dòng có NaN (ở bất kỳ cột nào)
df[df.isna().any(axis=1)]

# Kiểm lại shape
df.shape

"""### Kết Quả

- `df` hiện không tồn tại giá trị NaN nào nữa.
- Số dòng giảm xuống tương ứng với số dòng đã tồn tại NaN trước đó (201 - 8 = 193).

## 5. Chuyển kiểu phù hợp cho các cột còn lại.
"""

# df info
df.info()

# sample
df.sample()

"""### Nhận Xét

Dựa trên `df.info()` và `.sample()` ở tên, chúng ta xác định các cột cần đổi như dưới đây.

- Lý do: Nhận đúng dạng kiểu số nếu đang nhận là object.

Các cột cần đổi:

```
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  

 18  bore               193 non-null    object -> float
 19  stroke             193 non-null    object -> float

 22  peak-rpm           193 non-null    object -> int

 25  price              193 non-null    object -> float
```
"""

# Kiểm lại giá trị thực tế của dữ liệu
df.loc[12, ['bore', 'stroke', 'peak-rpm', 'price']]

# Kiểm tra kiểu dữ liệu trước khi thực hiện
df[['bore', 'stroke', 'peak-rpm', 'price']].info()

# Đổi kiểu dữ liệu
# Dù price trông rất giống int nhưng sẽ dùng float từ thuộc tính tự nhiên của nó
df['bore'] = df['bore'].astype('float')
df['stroke'] = df['stroke'].astype('float')
df['peak-rpm'] = df['peak-rpm'].astype('int')
df['price'] = df['price'].astype('float')
df.info()

# Kiểm lại kiểu dữ liệu
df[['bore', 'stroke', 'peak-rpm', 'price']].info()

"""### Kết Quả

- Các cột đã có kiểu dữ liệu phù hợp với giá trị thực tế.
- Cụ thể các cột đã được cập nhật là: 'bore', 'stroke', 'peak-rpm', 'price'.

## 6. Chọn ra các cột số, chuẩn hóa thành `zscore`.

### Nhận Xét

- `df` có một số lượng lớn các cột có dạng số (numeric), bao gồm `int` và `float`.
"""

df.info()

df.dtypes

"""### Kế Hoạch

- Lọc ra những cột có `dtype` là kiểu số.
- Sử dụng `sklearn.preprocessing.StandardScaler` để `transform` từng cột tương ứng.
"""

# Chọn ra những cột có dạng số
df.select_dtypes(include=['int64', 'float64']).info()

# Lấy ra danh sách các cột này
columns_list = df.select_dtypes(include=['int64', 'float64']).columns.to_list()
columns_list

# import StandardScaler
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

# Thực hiện transform zscore
for column in columns_list:
    df[column + '_zscore'] = ss.fit_transform(df[[column]])

# Kiểm lại df
df.shape

# Xem sample
df.sample()

# Lấy ra các cột zscore
df[[ column + '_zscore' for column in columns_list]]

"""### Kết Quả

- Có tổng số 16 cột dạng số.
- Tất cả các cột dạng số đã được tạo cột zscore, tương ứng 16 cột thêm mới.
- Kích thước của `df` hiện tại là (193, 42), với 42 = 26 cột đã có + 16 cột mới.
"""