# -*- coding: utf-8 -*-
"""IE313-b04-bai03-baitap.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fOgSMdDqFqAD0m8OnZbixeKjQhqUt4kB

# Buổi 04 - Bài 03 - Bài Tập (Phần 01)

- MSSV: 25410291
- Họ Tên: Đinh Xuân Sâm
- GDrive: [IE313-b04-bai03-baitap.ipynb](https://colab.research.google.com/drive/1fOgSMdDqFqAD0m8OnZbixeKjQhqUt4kB?usp=drive_link)

## Yêu Cầu

- Đưa vào một df và tên quốc gia cụ thể.
- Trả về số lượng di cư của quốc gia đó tới Canada
- Các cột từ 1980 - 2013
- Mỗi cột là một năm
- Thêm cột tổng số ở cuối

## Nạp Dữ Liệu
"""

# Khai báo tên của dataset trước khi tải về
canada_dataset_url = "https://github.com/datasethub/ds105/raw/refs/heads/master/Canada.xlsx"
canada_dataset_file = "Canada.xlsx"

# Tải dataset
import requests

response = requests.get(canada_dataset_url)

with open(canada_dataset_file, "wb") as file:
    file.write(response.content)

print("Download complete!")

# cài đặt xlrd
!pip install xlrd

# import
import pandas as pd
import numpy as np

# đọc file excel
df_canada = pd.read_excel(
    canada_dataset_file,
    sheet_name='Canada by Citizenship',
    skiprows=range(20),
    skipfooter=2
)

df_canada.shape

# thông tin của dataset
df_canada.info()

# xem thử
df_canada.sample()

"""## Bài Làm

### Đổi Tên Cột
"""

# khai báo danh sách cột đổi cũ: mới
columns = {
    'OdName': 'Country',
    'AreaName': 'Continent',
    'RegName': 'Region'
}

# kiểm thử sau khi đổi
df_canada.rename(columns=columns, inplace=False).info()

# thực hiện và kiểm lại
df_canada.rename(columns=columns, inplace=True)
df_canada.info()

"""### Loại Bỏ Cột"""

# danh sách các cột cần bỏ
drop_collumns = ['AREA', 'REG', 'DEV', 'Type', 'Coverage']

# kiểm thử
df_canada.drop(columns=drop_collumns, inplace=False).info()

# thực hiện
df_canada.drop(columns=drop_collumns, inplace=True)
df_canada.info()

# liệt kê tên các nước để đảm bảo gọi đúng tên
# ví dụ Viet Nam thay vì Vietnam, hay vietnam, vv..
df_canada['Country'].unique()

"""### Tạo Hàm Chọn"""

# Đưa vào một df và tên quốc gia cụ thể.
# Trả về số lượng di cư của quốc gia đó tới Canada
# Các cột từ 1980 - 2013
# Mỗi cột là một năm
# Thêm cột tổng số ở cuối

def chon(df: pd.DataFrame, Country: str) -> pd.Series:
    # chọn ra quốc gia và tạo bản sao
    df_chon = df.loc[df['Country'] == Country].copy()
    # lấy các cột năm (các cột có name là số)
    years = [col_name for col_name in df.columns.to_list() if isinstance(col_name, int)]
    # tính tổng từ các năm và gán cột total
    df_chon['total'] = df_chon[years].sum(axis=1)
    # trả về series
    return df_chon

# Kiểm thử

chon(df_canada, 'Viet Nam')

"""### Hoàn Thành

- Hàm `chon()` đã được hoàn thành.
- Nhận vào `pd.DataFrame` và một tên nước.
- Trả về một `pd.Series` chứa dòng của nước đó, kèm một cột tổng.
"""